### ISSUE TITLE
I can't get the images to load on my browser

### ISSUE THREAD

**Issue by siddo0sidddo** [robertskmiles/elosort#1]
Everything works as it should except when I go to the webpages the image files are not there, the bounding boxes are. Also, when I click on view fullsize it comes up with this error:

403 Forbidden
Request forbidden -- authorization will not help

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cherrypy\_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "C:\Python27\lib\site-packages\cherrypy\_cprequest.py", line 686, in _do_respond
    self.hooks.run('before_handler')
  File "C:\Python27\lib\site-packages\cherrypy\_cprequest.py", line 116, in run
    raise exc
HTTPError: (403, None)

**Comment by robertskmiles** [comment]
I'm not able to replicate that, so I'm not sure.
One thing that might help is using 0.0.0.0 instead of 127.0.0.1.
Try adding
`'server.socket_host' : '0.0.0.0'`
to the config dictionary on line 249.
So instead of `{'server.socket_port': opts.port}`, you have `{'server.socket_port': opts.port, 'server.socket_host' : '0.0.0.0'}`
